name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:  # 1. Build job: run main.py
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install uv
        uv sync
    
    - name: Run Python script
      run: uv run python main.py

  test:  # 2. Test job: run pytest
    runs-on: ubuntu-latest
    needs: build  # Wait until build job is successful
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install uv
        uv sync
    
    - name: Run tests
      run: uv run pytest test_main.py -v
